# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
  fr: "Équipe STRUDEL"
  en: "STRUDEL team"
email: clement.mallet@ign.fr
description:
  fr: "super équipe de ouf"
  en: "A research team"
baseurl: "/strudel_academic" #"/strudel" # the subpath of your site, e.g. /blog
url: "https://www.umr-lastig.fr" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: umrlastig

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
#  - 'jekyll/scholar'

remote_theme: gaalcaras/academic

langs: ["fr", "en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "fr"

ACL:
  fr: "Journaux internationaux"
  en: "International Journals"
ACLN:
  fr: "Journaux nationaux"
  en: "National Journals"
ASCL:
  fr: "Autres articles"
  en: "Other articles"
ACTI:
  fr: "Conférences internationales"
  en: "International conferences"
ACTN:
  fr: "Conférences nationales"
  en: "National Conferences"
COM:
  fr: "Communications"
  en: "Communications"
OS:
  fr: "Chapitres d'ouvrages"
  en: "Book Chapters"
DO:
  fr: "Directions d'ouvrages"
  en: "Books"
AFF:
  fr: "Posters"
  en: "Posters"
AP:
  fr: "Rapports ou pré-publications"
  en: "Reports or preprints"
TH:
  fr: "Dissertations (thèses)"
  en: "Dissertations (PhD theses)"
INV:
  fr: "Conférences invitées"
  en: "Invited Talks"
PV:
  fr: "Vulgarisation"
  en: "Popularization"

# scholar:
#   style: apa
#   locale: en
#
#   sort_by: none
#   order: ascending
#
#   group_by: none
#   group_order: ascending
#
#   source: ./_bibliography
#   bibliography: references.bib
#   bibliography_template: ""
#
#   replace_strings: true
#   join_strings:    true
#
#   use_raw_bibtex_entry: false
#
#   details_dir:    bibliography
#   details_layout: bibtex.html
#   details_link:   Details
#
#   query: "@*"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
