# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:
  fr: "STRUDEL"
  en: "STRUDEL"
title_html: "<b>STRUDEL</b>"
logo: assets/images/icons/logo_strudel.png
email: clement.mallet@ign.fr
description:
  fr: "Équipe de recherche du laboratoire LaSTIG sur les structures spatio-temporelles pour l'analyse des territoires"
  en: "Research team of the LaSTIG lab on spatio-temporal structures for spatial dynamics of territories"
baseurl: "/strudel" #"/strudel" # the subpath of your site, e.g. /blog
url: "https://www.umr-lastig.fr" # the base hostname & protocol for your site, e.g. http://example.com
cc: by-nc
publication_filter: 3
# nav_ext_links:
#   - name: LaSTIG
#     url: https://www.umr-lastig.fr

#twitter_username: jekyllrb
github_username: umrlastig

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
#  - 'jekyll/scholar'

remote_theme: gaalcaras/academic

langs: ["fr", "en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "fr"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
